### ISSUE TITLE
Run by jupyter

### ISSUE THREAD

**Issue by huangwei2013** [microsoft/interpret#14]
It's  not as issue but a note , hoping helpful for newegg :)

I run this on Win10 + Anaconda-Jupyter + Python3.7

Some trouble:
     Cannot search & install interpret in Anaconda, so I install by pip, and include the lib in code

```

import sys
sys.path.append("D:\software\python\python37\Lib\site-packages") # my python3.7 location

import numpy as np
x_train = np.random.random((100, 20))
y_train = np.random.randint(2, size=(100, 1))

from interpret.glassbox import ExplainableBoostingClassifier
ebm = ExplainableBoostingClassifier()
ebm.fit(x_train, y_train)
ebm_global = ebm.explain_global()

from interpret import show
from interpret import set_show_addr, get_show_addr
set_show_addr(('127.0.0.1', 7001)) # Will run on 127.0.0.1 at port 7001
show(ebm_global) 
```

I got result in Jupyter, while make a try visit by brower with "http://127.0.0.1:7001/", page show me "Internal Server Error", and Jupyter show tips ( not a problem but just wondering what happened):

> Traceback (most recent call last):
>   File "D:\hw\software\Anaconda3\lib\site-packages\gevent\pywsgi.py", line 976, in handle_one_response
>     self.run_application()
>   File "D:\hw\software\Anaconda3\lib\site-packages\gevent\pywsgi.py", line 923, in run_application
>     self.result = self.application(self.environ, self.start_response)
>   File "D:\software\python\python37\Lib\site-packages\interpret\visual\dashboard.py", line 187, in __call__
>     app = self.pool[ctx_id]
> KeyError: 'favicon.ico'
> 2019-05-20T10:43:12Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '59185', 'HTTP_HOST': '127.0.0.1:7001', (hidden keys: 23)} failed with KeyError

**Comment by interpret-ml** [comment]
Thanks for bringing this up @huangwei2013 !

To add to that, for development we often work through a conda environment. We use pip install for interpret and jupyter. Then we run `python -m jupyter notebook` to ensure we use the environment's Jupyter, instead of the system installed one. Otherwise it often selects the wrong Python kernel for use.

In terms of "http://127.0.0.1:7001/", the root path does not provide anything right now and will return that system error. When you're in a Jupyter notebook, we provide access to "http://127.0.0.1:7001/{some_identifier}" for each visualization, whether it's a single graph or an interactive dashboard.

Ideally in the next update, we'll have a meaningful page that display at the root path, instead of the error you're witnessing now.

**Comment by huangwei2013** [comment]
thx.

A question, anywhere can we get ROADMAP of interpret.
For so many ML toolkits currently, we user may most likely will combine them together, so hoping to figure out every orientation

**Comment by interpret-ml** [comment]
Hi @huangwei2013

There's a very light ROADMAP in the README.md detailing immediate feature additions we'll be adding specific to EBM.

In terms of overall roadmap, we'll try to publicize it in the near future. There's still some areas we'd like to better gauge before setting any expectations.

Upon saying that, right now we're focusing on hardening the package (fixing bugs, getting the install working on more systems, and of course comprehensive documentation!)

**Comment by interpret-ml** [comment]
The URL at root path should work now. Closing out issue. Let us know if you have more issues. :)
