### ISSUE TITLE
Bump dash version

### ISSUE THREAD

**Issue by ecederstrand** [microsoft/interpret#47]
dash 1.0 was released on June 20, 2019 and 1.1 on August 5, 2019.

The currently supported dash==0.39 is from March 5, 2019.

Range-based instead of exact dependencies would help when building environments where other packages than interpret are installed.

**Comment by interpret-ml** [comment]
Hi @ecederstrand - appreciate you bringing this up.

In full agreement, pinning versions are not ideal. This is one of the issues we've been meaning to get around to.
Also looked at your PR, so far the changes seem very clean!

The main problem we're facing right now is that `dash-tables-experiments` dependency we use is no longer supported and may run into problems with the latest dash. At the time of interpret's pre/first-release, `dash-tables` was still actively reaching parity with the experimental version.

Right now we're upgrading our tests and build system to run selenium so that we can move fast on transitioning to `dash-tables` amongst other changes. The tests will be available on `master`  branch in next release within 1-2 days from now.

Thanks for working on the changes to bump dash, it certainly helps this hurdle!

**Comment by ecederstrand** [comment]
Cool, thanks for the update! I hadn't seen that `dash-tables-experiments` is discontinued.

**Comment by ecederstrand** [comment]
Seems fixed with version 0.1.14. Thanks!
