### ISSUE TITLE
increase cost for predicting minority class?

### ISSUE THREAD

**Issue by peractio** [microsoft/interpret#54]
Does the ExplainableBoostingClassifier have a mechanism for dealing with imbalanced data?

**Comment by interpret-ml** [comment]
Hi @peractio, 

In practice, EBM should work fine for moderately unbalanced class distributions. One option would be to use a sampling technique (like those from the imbalanced-learn project: https://github.com/scikit-learn-contrib/imbalanced-learn) to re-balance the class distribution. 

An item on our backlog is adding instance level weights to the classifier, which might further help. It's good to know this would be valuable for you!

-InterpretML Team

**Comment by peractio** [comment]
@interpret-ml If you have not started work on this, may I implement it? Sampling techniques don't work well with my data due to the presence of a lot of binary values and the size of the dataset

I will take a look at the codebase, but may not be as confident if C/C++ portions need to be modified

**Comment by interpret-ml** [comment]
Hi @peractio -- We haven't started active work on this feature yet, but have had a couple of discussions on how it might be implemented.  We still have some unresolved questions about the best way to handle bagging, and the error bars when weights are involved.

Implementing weights will require changes to the C++ code.

-InterpretML team

**Comment by peractio** [comment]
@interpret-ml Thanks for the update, and for working on this! Those are very important questions, and I had gathered that the Python modifications required seem much smaller than the C++ ones

Out of curiosity, what do you mean by "best way to handle bagging"? Is it the parallelization aspect?

**Comment by richcaruana** [comment]
It's not a question of parallelization.  Has to do with what the right way to deal with weights is when bagging.  Here's a though experiment: you have a data set with 1000 training points each of which has weight 1 --- i.e., the usual setting with unweighted data.  To do bagging, you draw a bootstrap sample from the training data by drawing a new sample of 1000 points by sampling with replacement.  Some points will end up in the sample 2, 3 or possibly even 4 times, and about one third of the points won't end up in the sample at all.  So far this is all normal.  

But what happens if we take the same data set of 1000 points, and put weight 100 on each point.  One interpretation of this is that we've duplicated each point 100 times, so the data set now contains 100,000 points, but only 1000 unique points.  Now if you do bootstrap sampling, do you: a) draw a new sample of 100,000 points by sampling with replacement from the original sample prior to weights; or b) draw a sample of size 1000 points from the weighted points (keeping the weights on the points)?  Solution "a" is what bagging would have done if you hadn't used weights on samples but had just left all the copies in the data set to begin with.  But bagging doesn't work as well in this setting because you're going to get something like 85-115 samples of each point in each bagged sample, and this hinders bagging's ability to train different models.  Solution "b" probably works better from the point of view of bagging because the bagged samples are truly more different from each other, but then it means that having 100,000 points that consists of 100 copies of each point is different than what the algorithm does when it has 1000 points each with weight 100.  

We're leaning towards "a" so that if you use weights to reduce the size of your dataset by replacing duplicated points with single points with integer weights, then the behavior of the algorithm will be the same with and without weights.  Then there's a different question about how to interpret fractional weights, but let's ignore that for now.

Can you tell us more about your setting, how you're planning to use weights, and what behavior you would expect or want?

Thanks!
