### ISSUE TITLE
Why the attr_idxs is reversed, is it a bug? 

### ISSUE THREAD

**Issue by ZebinYang** [microsoft/interpret#83]
https://github.com/microsoft/interpret/blob/71c8d4f7a537ca7ed98f8bc4fdc2899e93405094/python/interpret-core/interpret/glassbox/ebm/utils.py#L57. 

The attr_idxs is reversed in the latest commit, does this mean the attribute_set_models is transposed somewhere. If not, this may be a bug.

**Comment by interpret-ml** [comment]
Hi @ZebinYang, 

Thanks for bringing this up! We had an internal data structure change between the Python code and the C++ layer, so the reversal was intentional! ```attr_idxs``` only has more than 1 element when there is an interaction, and prediction/visualization of interactions should be correct in the latest release. 

Please let us know if you find any upstream issues from this change!

-InterpretML Team
